### ISSUE TITLE
Support of Clic & Pay 

### ISSUE THREAD

**Issue by mathis-ait** [ekyna/PayumPayzenBundle#1]
The PayumBundle seems to be compatible with Clic&Pay and not this package :/

**Comment by mathis-ait** [comment]
i make the Pull Request here : [https://github.com/ekyna/PayumPayzenBundle/pull/2](https://github.com/ekyna/PayumPayzenBundle/pull/2)

**Comment by ekyna** [comment]
Fixed by #2
